---

- name: Setup Ceph Repos
  block:
    - name: Install ceph trusted key for RHEL
      rpm_key:
        state: present
        key: https://download.ceph.com/keys/release.asc
      when: not offline or (offline is defined and offline == false)
        
    - name: Configure Online Ceph repository
      yum_repository:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description }}"
        baseurl: "{{ item.value.baseurl }}"
        enabled: yes        
        gpgcheck: "{{ item.value.gpgcheck }}"
        gpgkey: "{{ item.value.gpgkey }}"
        file: "offline"
      loop: "{{ lookup('dict', ceph_online) }}"
      when: offline is defined and offline

    - name: Configure Offline Ceph repository
      yum_repository:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description }}"
        baseurl: "{{ item.value.baseurl }}"
        enabled: yes        
        gpgcheck: "{{ item.value.gpgcheck }}"
        gpgkey: "{{ item.value.gpgkey }}"
      with_dict: "{{ ceph_offline) }}"
      when: not offline or (offline is defined and offline == false)
  when: ansible_distribution == 'RedHat'

- name: Install ceph-deploy
  yum:
    name: "{{ ceph_deploy_rpm }}"
    state: installed
    allow_downgrade: yes
  when: inventory_hostname in groups['master-server']

...
