---

# NOTE: K8S and CEPH REPOS ARE MAINTAINED IN THEIR RESPECTIVE ROLES

- import_tasks: offline.yml
  when: offline is defined and offline

- import_tasks: online.yml
  when: not offline or (offline is defined and offline == false)

...
