---

- name: Add docker config
  template:
    src: templates/daemon.json.j2
    dest: "/etc/docker/daemon.json"

- name: Restart Docker
  service:
    name: docker
    state: restarted

- name: 'Download images from harbor'
  docker_image:
    name: "{{ harbor_repo }}/{{ item[item.rfind('/')+1:] }}"
    push: no
    pull: yes
  with_items:
    - "{{ kube_images }}"

- name: 'Retag local images back to original name'
  shell: "docker tag {{ harbor_repo }}/{{ item[item.rfind('/')+1:] }} {{ item }}"
  with_items:
    - "{{ kube_images }}"
