---
# TFPlenum
version: 3.0
debug_enabled: true
install_user: root
install_group: root
install_dir: /opt/rock
sysctl_file: /etc/sysctl.d/rock.conf
fqdn: default.svc.cluster.local

# Redis
redis_sentinel_port: 26379

# Elasticsearch
elastic_cluster_name: rock
elastic_fqdn: "elasticsearch.{{ fqdn }}"
elastic_port: 9200

# Kibana
kibana_fqdn: "kibana.{{ fqdn }}"

# If you have licensing for x-pack set variable to true.
xpack_license: 'true'

# Kubernetes
kubernetes_conf_file: /etc/kubernetes/admin.conf
kube_dir: "{{ install_dir }}/kubernetes"


# Bro
pulled_pork_oinkcode: 796f26a2188c4c953ced38ff3ec899d8ae543350
bro_rockscripts_repo: https://github.com/rocknsm/rock-scripts.git
pulled_pork_repo: https://github.com/shirkdog/pulledpork.git

# Kafka
kafka_fqdn: "kafka.{{ fqdn }}"
kafka_port: 9092
kafka_retention: 168

# VERSIONS
kube_state_ver: "v1.3.0"
kube_rpm_version: "1.9.7"
kube_image_version: "v1.9.7"
harbor_ver: "1.4.0"
metallb_ver: "v0.3.1"
busybox_ver: "1.27.2"
k8s_ver: "1.14.7"
elastic_ver: '6.2.4'
coreos_version: 1688.5.3

# Common
package_list:
  - cockpit-160-1.el7.centos
  - cockpit-dashboard-160-1.el7.centos
  - cockpit-machines-160-1.el7.centos
  - cockpit-networkmanager-160-1.el7.centos
  - cockpit-packagekit-160-1.el7.centos
  #- cockpit-storaged - this is currently broken TODO: we need to look into this. See: https://github.com/tfplenum/rock/issues/323
  - cockpit-system-160-1.el7.centos
  - python-gobject
  - python-docker-py.noarch
  - nload

# RockNSM
#rocknsm_baseurl: https://packagecloud.io/rocknsm/2/el/7/$basearch
#rocknsm_gpgurl: https://packagecloud.io/rocknsm/2/gpgkey
rocknsm_baseurl: 'https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/epel-7-$basearch/'
rocknsm_gpgurl: 'https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/pubkey.gpg'

ansible_controller_ip: "{{ ansible_env[\"SSH_CLIENT\"].split()[0] }}"

offline_repo_base: "http://{{ ansible_controller_ip }}/offlinerepo"
harbor_port: 81
harbor_project: "library"
harbor_repo: "{{ ansible_controller_ip }}:{{ harbor_port }}/library"
CentOS_Repos:
  - "Base"
  - "CR"
  - "Debuginfo"
  - "fasttrack"
  - "Media"
  - "Sources"
  - "Vault"
...
