---

- name: Create Elasticsearch directory
  file:
    path: "{{ elastic_dir }}"
    owner: root
    group: root
    mode: 0644
    state: directory

- name: 'Download Elasticsearch container'
  docker_image:
    name: "{{ elastic_image }}:{{ elastic_ver }}"

- name: Copy Files
  copy:
    src: "{{ item }}"
    dest: "{{ elastic_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - elastic-namespace.yml
    - elasticsearch-discovery-service.yml
    - elasticsearch-cluster-ip-service.yml
    - elasticsearch-loadbalancer-service.yml

- name: Install Templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ elastic_dir }}/{{ item }}"
    group: "{{ es_group }}"
    owner: "{{ es_user }}"
    mode: u+rw,g+rw
  with_items:
    - elasticsearch-definition.yml
