---
- name: Install Repo
  yum:
    name: "centos-release-gluster{{ gluster_ver | replace('.','') }}"
    state: present
  when: ansible_distribution == 'CentOS'

- name: "Manually install repo on Red Hat"
  yum_repository:
    baseurl: "http://mirror.centos.org/centos/7/storage/x86_64/gluster-{{ gluster_ver }}/"
    description: "Gluster repository"
    gpgcheck: no
    name: "CentOS-Gluster{{ gluster_ver }}"
  when: ansible_distribution == 'RedHat'