######################################################
################# Setup Kafka ########################
######################################################
---
- import_tasks: 05_zk_install.yml
- import_tasks: 10_kafka_install.yml
- import_tasks: 15_kafka_remote.yml
