#######################################################
###################  Kubernetes Repo ###############
#######################################################
---

- name: "Setup Kubernetes Online Repo"
  yum_repository:
    baseurl: "{{ item.value.baseurl }}"
    description: "{{ item.value.description }}"
    gpgcheck: "{{ item.value.gpgcheck }}"
    gpgkey: "{{ item.value.gpgkey }}"
    name: "{{ item.value.name }}"
    enabled: true
  with_dict: "{{ kube_online }}"
  when: not offline or (offline is defined and offline == false)

- name: "Setup Kubernetes Offline Repo"
  yum_repository:
    baseurl: "{{ item.value.baseurl }}"
    description: "{{ item.value.description }}"
    gpgcheck: "{{ item.value.gpgcheck }}"
    gpgkey: "{{ item.value.gpgkey }}"
    name: "{{ item.value.name }}"
    enabled: true
  with_dict: "{{ kube_offline }}"
  when: offline is defined and offline

...
