#######################################################
###################  Kubernetes Install ###############
#######################################################
---

- name: 'Install Kubernetes packages'
  yum:
    name: "{{ item }}"
    state: 'installed'
    allow_downgrade: yes
  with_items:
    - "kubeadm-{{ kube_rpm_version }}"
    - "kubelet-{{ kube_rpm_version }}"
    - "kubectl-{{ kube_rpm_version }}"
  register: installed_packages
  notify:
    - restart kubelet

- name: 'Install Kubernetes support packages'
  yum:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - "docker"
    - "device-mapper-persistent-data"
    - "lvm2"
    - "ebtables"
    - "ethtool"
  register: installed_packages
  notify:
    - restart docker

- name: Install Cockpit for Kubernetes
  yum:
    name: cockpit-kubernetes
    state: installed

...
