apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moloch-remote
  labels:
    component: moloch-remote
spec:
  serviceName: moloch-remote
  replicas: {{ groups['remote-sensors'] | length }} #{{ groups['moloch'] | length }}
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      component: moloch-remote
  template:
    metadata:
      labels:
        component: moloch-remote
    spec:
      hostNetwork: true
      containers:
      - name: "moloch"
        image: "{{ moloch_image}}:{{ moloch_tag }}"
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_NICE
        ports:
          - containerPort: {{ moloch_port }}
            name: webgui
        volumeMounts:
        - name: vars
          mountPath: /etc/icdm/
        - name: templates
          mountPath: /etc/icdm/templates/
        - name: configs
          mountPath: /etc/icdm/conf/
        - name: data
          mountPath: "{{ moloch_pcap_path }}"
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          path: {{ pcap_folder }}
      - name: vars
        configMap:
          name: vars
      - name: configs
        configMap:
          name: moloch
          items:
          - key: config.ini.conf
            path: config.ini.conf
      - name: templates
        configMap:
          name: moloch
          items:
          - key: config.ini.tmpl
            path: config.ini.tmpl
      nodeSelector:
        moloch: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - moloch-remote
              - key: node
                operator: In
                values:
                - remote-sensor
            topologyKey: "kubernetes.io/hostname"
